bulan_pembelian = ('januari', 'februari', 'maret', 'april', 'mei','juni', 'juli', 'agustus', 'september', 'oktober', 'november', 'desember')
print(bulan_pembelian[0])
print(bulan_pembelian[5])
print(bulan_pembelian[-1])
print(bulan_pembelian[-2])
